baseURL = "https://datos7506-fiuba.github.io/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Organización de Datos 75.06/95.58"
theme = "hugo-theme-docdock"
themesdir = "./themes"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
# 
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"


[markup]
[markup.goldmark.renderer]
unsafe = true

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>Drive</h3>"
name = "<img src='/images/google-drive-brands.svg' color='white' height='20px' width='20px'  style='vertical-align:middle;margin:0px 5px'></img><label>Drive</label>"
identifier = "drive"
url = "https://drive.google.com/drive/folders/16WyWC1HBv2dLF3rPTlhrK0OXw3G3hbhh"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-slack'></i><label>Slack</label>"
url = "https://organizaciondedatoshq.slack.com"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-users'></i> <label>Equipo</label>"
identifier = "hugodoc"
url = "/"
weight = 20

